server:
  port: 8771
spring:
  application:
    name: config-client-test
eureka:
  instance:
      preferIpAddress: true
      instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/


