server:
  port: 8766
spring:
  application:
    name: admin-server
  output:
      ansi:
        enabled: ALWAYS
eureka:
  instance:
      preferIpAddress: true
      instanceId: ${spring.application.name}:${server.port}
      lease-renewal-interval-in-seconds: 60
      health-check-url-path: /actuator/health
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
        #defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    registry-fetch-interval-seconds: 30
management:
  security:
    enabled: false
