server:
  port: 8862
spring:
  application:
    name: test-feign-client
  output:
      ansi:
        enabled: ALWAYS
eureka:
  instance:
      preferIpAddress: true
      instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/

common:
  fastjson:
    enable: true

# org.springframework.cloud.netflix.feign.FeignClientsConfiguration#HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true