server:
  port: 8781
spring:
  application:
    name: common-provider
  output:
      ansi:
        enabled: ALWAYS
eureka:
  instance:
      preferIpAddress: true
      instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/

common:
  fastjson:
    enable: true

#mybatis
mybatis:
  type-aliases-package: com.manager.common.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - com.manager.mybatis.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql