server:
  port: 8782
spring:
  application:
    name: health-indicator
  output:
      ansi:
        enabled: ALWAYS
eureka:
  instance:
      preferIpAddress: true
      instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/